
[theme]

# Primary accent for interactive elements 
primaryColor = '#3070B3'

# Background color for the main content area
backgroundColor = '#FFFFFF'

# Background color for sidebar and most interactive widgets 
secondaryBackgroundColor = '#F3DCD8'

# Color used for almost all text
textColor = '#31333F'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"